#!/bin/sh
# LIMpage_path="../Images_retrospective_python_with_soil_moisture"
# LIMpage_path="../Images_retrospective_python_no_soil_moisture_new_data_retrospective2"
# LIMpage_path="../Images_retrospective_python_no_soil_moisture_new_data_retrospective3"
# LIMpage_path="../Images_retrospective_python_no_soil_moisture_new_data_retrospective_lon"
# LIMpage_path="../Images_retrospective_python_with_soil_moisture_new_data_retrospective_lon"
# LIMpage_path="../Images_retrospective_stratosphere_combined_EOF"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_8_vars_2015"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_8_vars_climo_58-14"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_8_vars_climo_85-14"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_8_vars_climo_85-14_test"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_reproducing_8_vars_with_new_data_test1"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_reproducing_8_vars_with_new_data_test4"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_8_vars_5b_climo_95-14_EOF_58-14"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_test"
# LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/Images_retrospective_test"
# LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/CPC/Images_retrospective_8_vars_9b_sliding_climo_no_double_running_mean"
# LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/CPC/Images_retrospective_8_vars_9b2_sliding_climo_no_double_running_mean"
# LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/CPC/Images_retrospective_8_vars_9c_sliding_climo_add_offset"
# LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/CPC/Images_retrospective_8_vars_9d_sliding_climo_5_deg"
# LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/CPC/Images_retrospective_8_vars_9e_sliding_climo_no_double_running_mean_add_offset_simple_map"
LIMpage_path="/Projects/jalbers_process/CPC_LIM/yuan_ming/CPC/Images_retrospective_8_vars_9f_sliding_climo_no_double_running_mean_output_vars"
# LIMpage_path="/scratch/ycheng/CPC/Images_retrospective_8_vars_no_fullVariance"

rm -rf $LIMpage_path 
mkdir $LIMpage_path

mkdir "${LIMpage_path}/skill_pickles_regression"
mkdir "${LIMpage_path}/lim_t2m_retrospective"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression"
# mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/HitMissMaps"
# mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/TimeSeries"
# mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/VerifMaps"
# mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Maps"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Images_regression"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Images_regression/Maps"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Images_regression/Maps/T2m"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Images_regression/VerifMaps"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Images_regression/HitMissMaps/"
mkdir "${LIMpage_path}/lim_t2m_retrospective/wk34separate_regression/Images_regression/TimeSeries/"
